"""Regenerate the builtin policy YAML twins in policies/.

Run after changing a builtin: `python scripts/export_policies.py`. A unit test fails if the
twins drift from the Python definitions.
"""

from __future__ import annotations

from pathlib import Path

from jev_guard import Policy
from jev_guard.policies import BUILTIN_POLICIES
from jev_guard.policies.loader import dump_policy

OUT = Path(__file__).resolve().parent.parent / "policies"

HEADER = """\
# Builtin policy `{name}` - generated by scripts/export_policies.py; do not hand-edit.
# Copy this file to customize it, or start from it with `extends: {name}`.
# Validate your copy with: jev-guard policy validate path/to/file.yaml
"""


def render(name: str) -> str:
    return HEADER.format(name=name) + dump_policy(Policy.from_builtin(name))


def main() -> None:
    OUT.mkdir(exist_ok=True)
    for name in BUILTIN_POLICIES:
        (OUT / f"{name}.yaml").write_text(render(name), encoding="utf-8", newline="\n")
        print(f"wrote policies/{name}.yaml")


if __name__ == "__main__":
    main()
